plugins { id 'com.android.application' }

android {
    namespace 'it.liveasta.app'
    compileSdk 35

    defaultConfig {
        applicationId 'it.liveasta.app'
        minSdk 29
        targetSdk 35
        versionCode 10705
        versionName '1.07.5'
    }

    buildTypes {
        debug { applicationIdSuffix '' }
        release { minifyEnabled false }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
