import { chromium } from 'playwright';
import fs from 'node:fs';
fs.mkdirSync('qa-output',{recursive:true});
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:900}});
const errors=[];
page.on('pageerror',e=>errors.push({message:String(e),stack:e?.stack||''}));
await page.goto('https://davidegolisano-design.github.io/Test-asta/',{waitUntil:'networkidle',timeout:60000});
await page.getByRole('button',{name:/Banditore/i}).click();
await page.getByRole('button',{name:/Computer/i}).click();
await page.getByRole('button',{name:/Entra in una stanza/i}).click();
await page.waitForFunction(()=>/✅|532/.test(document.querySelector('#excel-status')?.textContent||''),null,{timeout:25000});
const sel=page.locator('#auction-room-select');
const value=await sel.locator('option').evaluateAll(opts=>opts.find(o=>o.textContent.trim()==='QA10P5T')?.value);
await sel.selectOption(value);
await page.locator('#auction-room-password').fill('qa0913');
await page.locator('#auction-wizard-next:visible, #btn-apri-plancia:visible').first().click();
await page.waitForTimeout(2000);
await page.screenshot({path:'qa-output/access-qa.png',fullPage:true});
const state=await page.evaluate(()=>({active:[...document.querySelectorAll('.screen.active')].map(e=>e.id),error:document.querySelector('#auction-room-error')?.textContent||'',selected:document.querySelector('#auction-room-select')?.value||'',body:document.querySelector('.screen.active')?.innerText?.slice(0,1600)||''}));
fs.writeFileSync('qa-output/access-qa.json',JSON.stringify({state,errors},null,2));
console.log(JSON.stringify({state,errors}));
await browser.close();
if(!state.active.includes('screen-auctioneer-board'))process.exit(1);