// Run with the same NODE_PATH as matchday-regression.cjs.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const {parseHTML}=require('linkedom');
const {document}=parseHTML(fs.readFileSync('index.html','utf8'));
document.readyState='complete';
document.getElementById('screen-auctioneer-board').classList.add('auctioneer-ui-mobile');
document.getElementById('auction-dashboard').classList.add('mode-mobile');
const view=document.getElementById('view-auction');
const ctx={document,console,requestAnimationFrame:f=>f(),MutationObserver:class{observe(){}},matchMedia:()=>({matches:true,addEventListener(){}}),addEventListener(){}};
ctx.window=ctx;vm.createContext(ctx);
vm.runInContext(fs.readFileSync('scripts/auctioneer-mobile-board.js','utf8'),ctx);
const left=document.getElementById('liveasta-mobile-timer-surface');
const right=document.getElementById('liveasta-mobile-info-surface');
view.classList.add('mobile-turn');
document.getElementById('auctioneer-turn-team').textContent='Squadra con nome lungo';
ctx.refreshLiveAstaMobileBoardDev();
assert.equal(left.querySelector('.liveasta-mobile-surface-main').textContent,'Squadra con nome lungo');
assert.ok(right.classList.contains('active'),'empty turn panel remains visible');
assert.equal(right.querySelector('.liveasta-mobile-surface-main').textContent,'Nessuna offerta');
const ranking=document.getElementById('sealed-ranking-auctioneer');
ranking.innerHTML='<div class="sealed-ranking-row"><span class="sealed-ranking-pos">1</span><strong class="sealed-ranking-team">FC DEMO</strong><span class="sealed-ranking-value">42</span></div>';
const source=ranking.innerHTML;
ctx.refreshLiveAstaMobileBoardDev();
assert.equal(right.querySelector('.liveasta-mobile-list-row strong').textContent,'FC DEMO');
assert.ok(right.querySelector('.liveasta-mobile-list-row').textContent.includes('42'));
assert.equal(ranking.innerHTML,source,'presentation never rewrites the authoritative ranking');
view.classList.remove('mobile-turn');view.classList.add('mobile-normal');
document.getElementById('countdown-display').textContent='12';
document.getElementById('current-value-display').textContent='85';
ctx.refreshLiveAstaMobileBoardDev();
assert.equal(left.querySelector('.liveasta-mobile-surface-main').textContent,'12');
assert.equal(right.querySelector('.liveasta-mobile-surface-main').textContent,'85');
assert.equal(right.querySelectorAll('.liveasta-mobile-list-row').length,0,'next auction clears old ranking');
view.classList.remove('mobile-normal');view.classList.add('mobile-turn');ranking.replaceChildren();
ctx.refreshLiveAstaMobileBoardDev();
assert.equal(right.querySelector('.liveasta-mobile-surface-main').textContent,'Nessuna offerta','cleared ranking returns to empty state');
console.log('Mobile turn, ranking and next-auction regression checks passed.');
